"use client";
import { Inter } from "next/font/google";
// import { CartProvider } from "./contexts/page";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import Home from "./page";
import { AppWrapper } from "./contexts/contextApi";
import NextTopLoader from "nextjs-toploader";
import { useEffect } from "react";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  let Mode = undefined;
  useEffect(() => {
    Mode = localStorage.getItem("darkMode") === "true" ? "dark" : "light";
  }, []);
  return (
    <html
      lang="en"
      className={
        //  localStorage.getItem("darkMode") === "true" ? "dark" : "light" }
        Mode
      }
    >
      <head>
        <title>CodesWear.com</title>
        <link rel="icon" sizes="512x512" href="/logo.jpg" type="image/ico" />
        <meta name="description" description="Generated by create next app" />
        <meta name="keywords" content="codeswear.com " />
      </head>

      <body
        className={`overflow-x-hidden dark:bg-[#1f2937] ${inter.className}`}
      >
        {/* <CartProvider> */}

        <Suspense>
          <AppWrapper>
            <div className="flex flex-col justify-between min-h-screen">
              <div>
                <Navbar />
                <NextTopLoader
                  color="#db2777"
                  crawlSpeed={400}
                  showSpinner={false}
                  speed={700}
                  showAtBottom={false}
                />
                {children}
              </div>
              <div>
                <Footer />
              </div>
            </div>
          </AppWrapper>
        </Suspense>
        {/* </CartProvider> */}
      </body>
    </html>
  );
}
