"use client"
import { Inter } from "next/font/google";
// import { CartProvider } from "./contexts/page";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import Home from "./page";
import { AppWrapper } from "./contexts/page";
import NextTopLoader from "nextjs-toploader";
import { useEffect } from "react";
import Head from "next/head";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"]})   


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  let Mode = undefined
  useEffect(()=>{
    Mode =  localStorage.getItem("darkMode") === "true" ? "dark" : "light" 
  },[])
  return (
    <html
      lang="en"
      className={
        //  localStorage.getItem("darkMode") === "true" ? "dark" : "light" }
        Mode
      }
    >
      <head>
        <title>CodesWear.com</title>
        <link rel="icon" sizes="512x512" href="/favicon.ico" type="image/ico" />
        <meta name="description" description="Generated by create next app" />
        <meta name="keywords" content="codeswear.com " />
      </head>

      <body className={inter.className}>
        {/* <CartProvider> */}

        <AppWrapper>
          <Suspense
            fallback={
              <div className="dark:bg-[#1f2937] mt-0 lg:mt-[14%] xl:mt-[2%] pb-[40%]">
                <div className=" sm:block hidden sm:ml-[35%] md:ml-[39%]  pt-36 lg:pt-32  xl:pt-40">
                  <div className="lds-ellipsis">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                  </div>
                </div>
                <h3 className="text-center sm:hidden block pt-28">
                  <div className="lds-ellipsis ">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                  </div>
                </h3>
                <h3 className="text-6xl font-sans relative bottom-28 mb-60 sm:text-start text-center sm:ml-[35%] md:ml-[39%] font-medium text-pink-600">
                  Loading...
                </h3>
              </div>
            }
          >
            <Navbar />
            <NextTopLoader
              color="#db2777"
              height={2.34}
              crawlSpeed={400}
              showSpinner={false}
              speed={700}
              showAtBottom={false}
            />
            {children}
            <Footer />
          </Suspense>
        </AppWrapper>
        {/* </CartProvider> */}
      </body>
    </html>
  );
}








